baseURL = 'https://lucaferroni.it/'
locale = 'it-it'
title = 'Luca Ferroni Home Page'
theme = 'congo'

languageName = "Italiano"
defaultContentLanguage = "it"

# Configurazione dei Menu per Congo
[languages]
  [languages.it]
    locale = "it-it"
    contentDir = "content"
    title = "Il Mio Blog Hacker"
    
    [languages.it.menu]
      [[languages.it.menu.main]]
        name = "Post"
        pageRef = "posts"
        weight = 10
      [[languages.it.menu.main]]
        name = "Tag"
        pageRef = "tags"
        weight = 20

[params]
  
    # Dice al tema Congo di mostrare la sezione posts nella homepage
    mainSections = ["posts"]

    # Istruisce Congo a caricare i parziali custom nella home
    homepageImageLayout = "profile"

    [params.author]
      name = "Luca `feroda` Ferroni aka `Lucafero`"
      bio = "Sviluppatore e appassionato di hacking"

      links = [
        { github = "https://github.com/feroda" },
        { linkedin = "https://linkedin.com/in/lucaferroni" },
        { facebook = "https://www.facebook.com/luca.ferroni.75/" },
        { instagram = "https://www.instagram.com/ferodafabriano/" }
      ]